pipeline {
    agent any
    parameters {
        booleanParam defaultValue: false, name: 'terraform_stage'
        booleanParam defaultValue: false, name: 'deploy_S3'
        booleanParam defaultValue: false, name: 'destroy_terraform'
    }
    options {
        ansiColor('xterm')
    }
    stages{
        stage('terraform stage') {
            when {expression{return params.terraform_stage}}
            steps {
                withAWS(credentials: 'AWS_Credentials', region: 'us-east-1') {
                    // some block
                    dir('terraform') {
                        sh '''
                            terraform init
                            terraform apply --auto-approve
                        '''
                    }
                }
            }
        }
         stage('deploy to S3') {
            when {expression{return params.deploy_S3}}
            steps {
                withAWS(credentials: 'AWS_Credentials', region: 'us-east-1') {
                    
                     sh '''
                            npm cache clean --force
                            rm -rf node_modules
                            rm -rf package-lock.json
                            npm install
                            npm run build
                            aws s3 cp build s3://bo-chen.click --recursive
                            aws s3 website s3://bo-chen.click/ --index-document index.html --error-document error.html
                        '''
                }
            }
        } 
        stage('destroy terraform') {
            when {expression{return params.destroy_terraform}}
            steps {
                withAWS(credentials: 'AWS_Credentials', region: 'us-east-1') {
                    // some block
                    dir('terraform') {
                        sh '''
                            terraform init
                            terraform destroy --auto-approve
                        '''
                    }
                }
            }
        }
    }    
}